# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Terraform@2
  inputs:
    TemplatePath: 'terraform'
    Arguments: 
    InstallTerraform: true
    Version: '0.12.17'
    UseAzureSub: true
    ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
    ConnectedServiceNameARM: 'Pay-As-You-Go(136f4268-7dd0-446b-ab31-ec197ff147d5)'
    ManageState: true
    SpecifyStorageAccount: true
    StorageAccountResourceGroup: 'akspochelloworldabc5-rg'
    StorageAccountRM: 'eepoctfstate'
    StorageContainerName: 'tfstate'

    
- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Pay-As-You-Go(136f4268-7dd0-446b-ab31-ec197ff147d5)'


- task: TerraformTaskV1@0
  inputs:
     provider: 'azurerm'
     command: 'apply'
     environmentServiceNameAzureRM: 'Pay-As-You-Go(136f4268-7dd0-446b-ab31-ec197ff147d5)'