# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
    - task: UseDotNet@2
      inputs:
        version: '3.0.x'

    - task: UseDotNet@2
      inputs:
        version: '2.2.x'
        packageType: runtime

    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      displayName: nuget restore
      inputs:
        restoreSolution: '$(solution)'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration Release' # Update this to match your need

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: '**/*.csproj'

    - task: CopyFiles@2
      displayName: copy terraform files
      inputs:
       SourceFolder: 'terraform/'
       Contents: '**.tf'
       TargetFolder: '$(build.artifactstagingdirectory)'
    
    - task: PublishBuildArtifacts@1
      displayName: create terraform artifact
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

    - task: Docker@2
      displayName: docker build and push
      inputs:
        containerRegistry: 'ACRServiceHelloWorld'
        repository: 'helloword_azpoc'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'
    - task: AzureCLI@2
      displayName: pwd ls
      inputs:
        azureSubscription: 'Pay-As-You-Go(136f4268-7dd0-446b-ab31-ec197ff147d5)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          pwd
          ls
          helm init -c
          
    - task: HelmDeploy@0
      displayName: helm package
      inputs:
        command: 'package'
        chartPath: 'manifests/helloworld/'
        updateDependency: true
    - task: AzureCLI@2
      displayName: helm push
      inputs:
        azureSubscription: 'Pay-As-You-Go(136f4268-7dd0-446b-ab31-ec197ff147d5)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          cd ../a
          ls
          docker login akspochelloworld.azurecr.io -p $(acrpassword) -u akspochelloworld > program.stdout 2> program.stderr
          az configure --defaults acr=akspochelloworld > program.stdout 2> program.stderr
          az acr helm repo add > program.stdout 2> program.stderr
          az acr helm push *.tgz --name akspochelloworld > program.stdout 2> program.stderr
        useGlobalConfig: true
        failOnStandardError: true
