# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
    - task: UseDotNet@2
      inputs:
        version: '3.0.x'

    - task: UseDotNet@2
      inputs:
        version: '2.2.x'
        packageType: runtime

    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration Release' # Update this to match your need

    - task: DotNetCoreCLI@2
      displayName: Test
      inputs:
        command: test
        projects: '**/*.csproj'

    - task: CopyFiles@2
      inputs:
       SourceFolder: 'terraform/'
       Contents: '**.tf'
       TargetFolder: '$(build.artifactstagingdirectory)'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

    - task: Docker@2
      inputs:
        containerRegistry: 'ACRServiceHelloWorld'
        repository: 'helloword_azpoc'
        command: 'buildAndPush'
        Dockerfile: 'Dockerfile'

    - task: HelmDeploy@0
      inputs:
        command: 'package'
        chartPath: 'manifests/helloworld/'
        chartVersion: '0.1.0'
        updateDependency: true
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Pay-As-You-Go(1)(136f4268-7dd0-446b-ab31-ec197ff147d5)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az acr helm push helloworld-0.1.0.tgz'