# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

resources:
- repo: self

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '5d911ca7-6668-422d-af12-f37d346a1529'
  imageRepository: 'pjangamazurepoc'
  containerRegistry: 'akspochelloworld.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'akspochelloworld418f-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  
stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        command: 'login'
    - upload: manifests
      artifact: manifests
      
- stage: Deploy
  displayName: Deploy stage

  jobs:
  - deployment: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'pjangamazurepoc.default'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: KubernetesManifest@0
            displayName: Create imagePullSecret
            inputs:
              action: createSecret
              secretName: $(imagePullSecret)
              dockerRegistryEndpoint: $(dockerRegistryServiceConnection)
          - task: KubernetesManifest@0
            displayName: Deploy tiller to Kubernetes cluster
            inputs:
              action: deploy
              manifests: |
                $(Pipeline.Workspace)/manifests/tiller.yml
              imagePullSecrets: |
                $(imagePullSecret)
              containers: |
                $(containerRegistry)/$(imageRepository):$(tag)
          - task: HelmDeploy@0
            displayName: helm init
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscription: 'Pay-As-You-Go(1)(136f4268-7dd0-446b-ab31-ec197ff147d5)'
              azureResourceGroup: 'firstapp-resources'
              kubernetesCluster: 'hello'
              useClusterAdmin: true
              namespace: 'default'
              command: 'init'
          - task: HelmDeploy@0
            displayName: helm repo update
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscription: 'Pay-As-You-Go(1)(136f4268-7dd0-446b-ab31-ec197ff147d5)'
              azureResourceGroup: 'firstapp-resources'
              kubernetesCluster: 'hello'
              command: 'repo'
              arguments: 'update'
          - task: Docker@2
            inputs:
              containerRegistry: 'akspochelloworld'
              command: 'login'

          - task: AzureCLI@2
            inputs:
              azureSubscription: 'Pay-As-You-Go(1)(136f4268-7dd0-446b-ab31-ec197ff147d5)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                helm repo update
                az configure --defaults acr=akspochelloworld
                az acr helm repo add
                helm repo update
                helm search hello
              
          - task: HelmDeploy@0
            displayName: helm hello world
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscription: 'Pay-As-You-Go(1)(136f4268-7dd0-446b-ab31-ec197ff147d5)'
              azureResourceGroup: 'firstapp-resources'
              kubernetesCluster: 'hello'
              command: 'upgrade'
              chartType: 'Name'
              chartName: 'akspochelloworld/helloworld'
              releaseName: 'helloworld'
              arguments: '--debug'
          - task: HelmDeploy@0
            displayName: helm ls
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscription: 'Pay-As-You-Go(1)(136f4268-7dd0-446b-ab31-ec197ff147d5)'
              azureResourceGroup: 'firstapp-resources'
              kubernetesCluster: 'hello'
              command: 'ls'
