apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: "2020-01-06T12:59:14Z"
  name: service-admin
  selfLink: /apis/rbac.authorization.k8s.io/v1/clusterrolebindings/service-admin
  uid: 20f5a9c3-d815-465d-b2f5-5a8adaad7052
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
