apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld-ingress
spec:
  rules:
     - http:
        paths:
          - path: /weather
            backend:
              serviceName: pjangamazurepoc
              servicePort: 80