apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld-ingress
spec:
  rules:
    - host: 52.247.233.234.xip.io
      http:
       paths:
         - path: /
           backend:
             serviceName: pjangamazurepoc
             servicePort: 80
