apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloworld-ingress
spec:
  rules:
    - host: 13.66.200.227.xip.io
      http:
       paths:
         - path: /weather
           backend:
             serviceName: pjangamazurepoc
             servicePort: 80
