apiVersion: apps/v1beta1
kind: Ingress
metadata:
  name: helloworld-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/tls-acme: 'true'
spec:
  tls:
    - hosts:
        - csharpfiddle.westeurope.cloudapp.azure.com
      secretName: tls-secret
  rules:
    - host: csharpfiddle.westeurope.cloudapp.azure.com
      http:
        paths:
          - path: /
            backend:
              serviceName: pjangamazurepoc
              servicePort: 80