apiVersion: v1
kind: Service
metadata:
    name: pjangamazurepoc
spec:
    type: ClusterIP
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    selector:
        app: pjangamazurepoc